### ISSUE TITLE
Attempt to invoke virtual method 'void com.kevin.zhang.minutes.myChart.MyYAxis.setAxisMaxValue(float)' on a null object reference

### ISSUE THREAD

**Issue by ZhangKuixun** [AndroidJiang/StockChart#47]
> 06-25 10:45:19.645 332-332/com.kevin.zhang E/AndroidRuntime: FATAL EXCEPTION: main
>                                                              Process: com.kevin.zhang, PID: 332
>                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kevin.zhang/com.kevin.zhang.minutes.MinutesActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.kevin.zhang.minutes.myChart.MyYAxis.setAxisMaxValue(float)' on a null object reference
>                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
>                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
>                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java)
>                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
>                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                  at android.os.Looper.loop(Looper.java:154)
>                                                                  at android.app.ActivityThread.main(ActivityThread.java:6077)
>                                                                  at java.lang.reflect.Method.invoke(Native Method)
>                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
>                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
>                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.kevin.zhang.minutes.myChart.MyYAxis.setAxisMaxValue(float)' on a null object reference
>                                                                  at com.kevin.zhang.minutes.MinutesActivity.setData(MinutesActivity.java:245)
>                                                                  at com.kevin.zhang.minutes.MinutesActivity.getOffLineData(MinutesActivity.java:355)
>                                                                  at com.kevin.zhang.minutes.MinutesActivity.onCreate(MinutesActivity.java:78)
>                                                                  at android.app.Activity.performCreate(Activity.java:6664)
>                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
>                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
>                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
>                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java) 
>                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
>                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                  at android.os.Looper.loop(Looper.java:154) 
>                                                                  at android.app.ActivityThread.main(ActivityThread.java:6077) 
>                                                                  at java.lang.reflect.Method.invoke(Native Method) 
>                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
>                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
> 

> public class MyBarChart extends BarChart {
> ...
>     @Override
>     public MyXAxis getXAxis() {
>         XAxis xAxis = super.getXAxis();
>         MyXAxis xAxis1 = (MyXAxis) xAxis;//error
>         return xAxis1;
>     }
> ...
> }

我使用的MPAndroidChart版本是3.0.3

**Comment by ZhangKuixun** [comment]
@AndroidJiang

**Comment by wsz9903011** [comment]
3.03 改了很多东西  有些去掉的方法 不是复制回去就可以的。
